version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: jdbc
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:7.4.7-apache
    build : .
    working_dir: /var/www/html
    command: ["apache2-foreground"]
    volumes:
      - "./:/var/www/html"
    ports:
      - 8083:80
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge